name: overlapping_time
description: A package for finding overlappings between given time ranges.
version: 0.1.0
repository: https://github.com/MasahiroLittleforest/overlapping_time

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  trotter: ^2.0.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
