name: overlapping_time
description: A package for finding overlappings between given time ranges.
version: 0.0.1
author: Littleforest <masahiro.littleforest@gmail.com>
repository: https://github.com/MasahiroLittleforest/overlapping_time

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  trotter: ^1.2.0
  basics: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

