name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-dry-run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze
        
      - name: Run tests
        run: flutter test
      
      - name: Set up credentials
        run: | 
          mkdir -p ~/.pub-cache 
          cat <<EOF > ~/.pub-cache/credentials.json
          {
          "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
          "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
          "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
          "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
          "expiration": 1570721159347
          }
          EOF
      
      - name: Publish Package
        run: flutter pub publish -f

      - name: Send notification to slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() 
